apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.angular.configMapName }}
data:
  config.json: {{ printf "\"{\"apiUrl\": \"/api/\", \"mapEnabled\": %s }\"" (.Values.features.mapEnabled | quote) }}
