apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.angular.configMapName }}
data:
  config.json: |
    "{"
      "\\\"apiUrl\\\": \\\"/api/\\\","
      {{ printf "\\\"mapEnabled\\\": %s }\"" (.Values.features.mapEnabled | quote) }}
    "}"
